services:
  products:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: products_subgraph_qa
    ports:
      - "4102:4002"
    env_file:
      - .env.qa
    environment:
      - NODE_ENV=qa
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
