services:
  products_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    container_name: products_subgraph_prod
    ports:
      - "4002:4002"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
