services:
  blog-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: blog-service
    ports:
      - "9005:9005"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
