services:
  products:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: products_subgraph
    ports:
      - "4002:4002"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
