services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: product-service
    ports:
      - "9002:9002"
    networks:
      - ekoru-network

networks:
  ekoru-network:
    external: true
